name: UI Tests

on:
  push:
    branches: ['*']
  pull_request:
    branches: ['*']

jobs:
  ui-test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: Install dependencies
        run: npm ci
      - name: Lint (ESLint)
        run: npm run lint
      - name: Check formatting (Prettier)
        run: npm run format:check
      - name: Install Playwright Browsers
        run: npx playwright install chromium --with-deps
      - name: Run UI tests
        run: npx playwright test testing/e2e
      - name: Ensure test-results directory exists
        run: mkdir -p test-results/
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: ui-test-report
          path: playwright-report/
          retention-days: 30
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: ui-test-results
          path: test-results/
          retention-days: 30
